# Generated by Django 6.1.1 on 2026-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('VENDEDOR', 'Vendedor')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.AddField(
            model_name='perfil',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='accounts.rol'),
        ),
    ]
